### PR TITLE
fix: trying to fix #332 with arbitrary heuristics

### LINKED ISSUE #332: Unexpected velocity at end of drag gesture
**Describe the bug**
Velocity seems to only be recalculated on movement events, making the last velocity likely to be inaccurate. This is notable mostly in cases where movement has stopped entirely.

**Sandbox**
https://codesandbox.io/s/use-gesture-drag-velocity-at-gesture-end-tu9kr?file=/src/index.js
Where it can be noted that dropping the draggable element after having ceased movement often still produces velocity and subsequent animation.

**Commentary**
In the sandbox linked above it might seem like a simple threshold test could be made and if the velocity is below it then further animation is avoided. That would work for probably most cases but would fail for high velocities that are possible after an abrupt halt to the movement (the demo button simulates that scenario). It could probably be worked around with a fairly simple timestamp test but this seems like a something the library could handle without detriment to other use cases.

**Information:**
 - Use Gesture version: 10
 - Device: macbook
 - OS: macOS
 - Browser: Brave

**Checklist:**
  - [ ] I've read the [documentation](https://use-gesture.netlify.app/).
  - [ ] If this is an issue with drag, I've tried setting `touch-action: none` to the draggable element.

### PR DESCRIPTION
**Pull request by dbismut**
This is an alternative to #337, which **does** compute velocity on the `last` event when the timestamp delta is greater than an arbitrary value (here set to `32 ms`).

I've added a console.log in the gesture-simplest demo (http://localhost:4000/gesture-simplest after running `pnpm demo:dev`, which prints the timestamp delta between the last event (`pointerup`) and before last event (`pointermove`), the movement `delta`, and the `velocity`.

@stokesman, let me know if that kinda fixes it for you, you can tweak the value to see if you get better results with your demo.

### CODE REVIEW

File: packages/core/src/engines/Engine.ts [hunk 1]
```diff
@@ -4,6 +4,21 @@ import { call } from '../utils/fn'
...
+ * The lib doesn't compute the kinematics on the last event of the gesture
+ * (i.e. for a drag gesture, the `pointerup` coordinates will generally match the
+ * last `pointermove` coordinates which would result in all drags ending with a
+ * `[0,0]` velocity). However, hen the timestamp difference between the last
+ * event (ie pointerup) and the before last event (ie pointermove) is greater
+ * than BEFORE_LAST_KINEMATICS_DELAY, the kinematics are computed (which would
+ * mean that if you release your drag after stopping for more than
+ * BEFORE_LAST_KINEMATICS_DELAY, the velocity will be indeed 0).
+ *
+ * See https://github.com/pmndrs/use-gesture/pull/337 for more details.
```
Comment (stokesman) [inline packages/core/src/engines/Engine.ts:17]: Would linking the original issue be better? Though the comment I think wraps it up well enough on its own.
```suggestion
 * See https://github.com/pmndrs/use-gesture/issues/332 for more details.
```

**Review by stokesman — COMMENTED** [review]
From my testing this works flawlessly. The 32ms value seems fine and I felt like it allows both intentional throw gestures and still drops without surprises. 🎉
