### PR TITLE
Remove react types from core

### LINKED ISSUE #507: Typescript: Type incompatibility error when using Gesture with the vanilla package
**Describe the bug**
When using the vanilla package in combination with Typescript, the `Gesture` class shows a type incompatibility error for the handlers.

After looking a bit through the underlying type definitions I noticed that the `Target` type in `packages/core/src/types/utils.ts` depends on `React.RefObject` even though the core package does not have a dependency on React types. This results in `Target` to resolve to `any` instead and causes the original error.

```ts
// packages/core/src/types/utils.ts:
export type Target = EventTarget | React.RefObject<EventTarget>
```

As a workaround additionally installing `@types/react` solves the issue.

**Sandbox**
https://codesandbox.io/s/nifty-diffie-8mfxcw?file=/src/index.ts:0-114
```ts
import { Gesture } from "@use-gesture/vanilla";

new Gesture(
  window,
  {
    onDrag: (state) => { /* ... */ }
  },
  {}
);
```

**Information:**
 - Use Gesture version: v10.2.15

**Checklist:**
  - [x] I've read the [documentation](https://use-gesture.netlify.app/).

### PR DESCRIPTION
**Pull request by dbismut**
Fix #507

### CODE REVIEW

File: packages/core/src/types/handlers.ts [hunk 1]
```diff
@@ -28,16 +29,9 @@ export type UserHandlers<T extends AnyHandlerEventTypes = EventTypes> = {
   onHover: Handler<'hover', check<T, 'hover'>>
 }
 
-export type ReactDOMAttributes = Omit<
-  React.DOMAttributes<EventTarget>,
-  'children' | 'dangerouslySetInnerHTML' | keyof UserHandlers
->
-
-type NativeHandlersKeys = keyof ReactDOMAttributes
+type NativeHandlersKeys = keyof DOMHandlers
```
Comment (SteveoKr) [inline packages/core/src/types/handlers.ts:32]: The `Omit` to prevent interference between the DOMHandlers and UserHandlers is missing.

```suggestion
type NativeHandlersKeys = keyof Omit<DOMHandlers, keyof UserHandlers>
```

**Review by SteveoKr — CHANGES_REQUESTED** [review]
Thank you for opening the PR! 
I noticed there is still a problem with the type for the onDrag state.
See: https://codesandbox.io/s/hopeful-ishizaka-vdf6by?file=/src/index.ts

After looking at your changes I noticed you forgot to add the `Omit` type to remove the UserHandlers from the new DOMHandlers.
I think re-adding it should solve the issue.

**Comment by dbismut** [comment]
Indeed, you're right @SteveoKr, I just added your suggestion :) I'll release an update in a few minutes on npm. Thanks again!
